---
Name: Heyday Elastica Config
---
Injector:
  Heyday\Elastica\SilverStripe\ReindexTask:
    constructor:
      - %$Heyday\Elastica\ElasticaService
  Heyday\Elastica\SilverStripe\Searchable:
    constructor:
      - %$Heyday\Elastica\ElasticaService
  ManyManyList:
    class: Heyday\Elastica\SilverStripe\ManyManyList