---
Name: Heyday Elastica Config
---
Injector:
  Heyday\Elastica\ReindexTask:
    constructor:
      - %$Heyday\Elastica\ElasticaService
  Heyday\Elastica\Searchable:
    constructor:
      - %$Heyday\Elastica\ElasticaService
  ManyManyList:
    class: Heyday\Elastica\ManyManyList

CleanupJob:
  is_enabled: true