Injector:
  Heyday\Elastica\SilverStripe\ReindexTask:
    constructor:
      - %$Heyday\Elastica\ElasticaService
  Heyday\Elastica\SilverStripe\Searchable:
    constructor:
      - %$Heyday\Elastica\ElasticaService
